# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./
    binary: gmx
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Homebrew tap
brews:
  - name: gmx
    repository:
      owner: razpinator
      name: homebrew-tap
    homepage: "https://github.com/razpinator/gmx"
    description: "A Golang based code/file generation tool that feeds data into templates"
    license: "MIT"
    test: |
      system "#{bin}/gmx --help"

# Scoop bucket
scoops:
  - name: gmx
    repository:
      owner: razpinator
      name: scoop-bucket
    homepage: "https://github.com/razpinator/gmx"
    description: "A Golang based code/file generation tool that feeds data into templates"
    license: "MIT"

# Linux packages
nfpms:
  - package_name: gmx
    homepage: "https://github.com/razpinator/gmx"
    description: "A Golang based code/file generation tool that feeds data into templates"
    maintainer: "razpinator <your-email@example.com>"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
